"use strict";
var msg = "Hey Abu Huraira i have started learning typescript";
var myname = "I am Muzammal Hussain";
console.log(msg);
console.log(myname);
var num1 = 1;
var num2 = 2;
var num3 = 3;
var num4 = 4;
var num5 = 5;
var num6 = 6;
var num7 = 7;
var num8 = 8;
var num9 = 9;
var num10 = 10;
var sum = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10;
console.log(sum);
var product = num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10;
console.log(product);
var diff = product - sum;
console.log(diff);
var div = num10 / num5;
console.log(div);
var allop1 = num1 - num4 * num6 + num10;
console.log(allop1);
var allop2 = num2 - num4 * num6 + num8;
var allop3 = num1 - num3 * num5 + num7;
var allop4 = num3 - num6 * num6 + num10;
console.log(allop2);
console.log(allop3);
console.log(allop4);
